import type { Metadata } from "next";
import { Comic_Neue } from "next/font/google";
import "./globals.css";
import SessionProvider from "@/components/providers/SessionProvider";
import { Toaster } from "@/components/ui/sonner";
import ConditionalNavigation from "@/components/ConditionalNavigation";

const comicNeue = Comic_Neue({
  variable: "--font-comic-neue",
  subsets: ["latin"],
  weight: ["300", "400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${comicNeue.variable} antialiased`}
      >
        <SessionProvider>
          <ConditionalNavigation />
          {children}
        </SessionProvider>
        <Toaster />
      </body>
    </html>
  );
}
